#pragma once

#include <algorithm>
#include <array>
#include <string>
#include <string_view>

#include "z64save.h"

namespace PalAssetLocalization {

struct Entry {
    std::string_view base;
    std::string_view ger;
    std::string_view fra;
    std::string_view esp;
};

inline constexpr std::array<Entry, 254> kEntries = {{
    { "do_action_static/gDoActionAttackENGTex", "do_action_static/gDoActionAttackGERTex", "do_action_static/gDoActionAttackFRATex", "do_action_static/gDoActionAttackESPTex" },
    { "do_action_static/gDoActionCheckENGTex", "do_action_static/gDoActionCheckGERTex", "do_action_static/gDoActionCheckFRATex", "do_action_static/gDoActionCheckESPTex" },
    { "do_action_static/gDoActionClimbENGTex", "do_action_static/gDoActionClimbGERTex", "do_action_static/gDoActionClimbFRATex", "do_action_static/gDoActionClimbESPTex" },
    { "do_action_static/gDoActionCurlENGTex", "do_action_static/gDoActionCurlGERTex", "do_action_static/gDoActionCurlFRATex", "do_action_static/gDoActionCurlESPTex" },
    { "do_action_static/gDoActionDanceENGTex", "do_action_static/gDoActionDanceGERTex", "do_action_static/gDoActionDanceFRATex", "do_action_static/gDoActionDanceESPTex" },
    { "do_action_static/gDoActionDecideENGTex", "do_action_static/gDoActionDecideGERTex", "do_action_static/gDoActionDecideFRATex", "do_action_static/gDoActionDecideESPTex" },
    { "do_action_static/gDoActionDiveENGTex", "do_action_static/gDoActionDiveGERTex", "do_action_static/gDoActionDiveFRATex", "do_action_static/gDoActionDiveESPTex" },
    { "do_action_static/gDoActionDownENGTex", "do_action_static/gDoActionDownGERTex", "do_action_static/gDoActionDownFRATex", "do_action_static/gDoActionDownESPTex" },
    { "do_action_static/gDoActionDropENGTex", "do_action_static/gDoActionDropGERTex", "do_action_static/gDoActionDropFRATex", "do_action_static/gDoActionDropESPTex" },
    { "do_action_static/gDoActionEnterENGTex", "do_action_static/gDoActionEnterGERTex", "do_action_static/gDoActionEnterFRATex", "do_action_static/gDoActionEnterESPTex" },
    { "do_action_static/gDoActionExplodeENGTex", "do_action_static/gDoActionExplodeGERTex", "do_action_static/gDoActionExplodeFRATex", "do_action_static/gDoActionExplodeESPTex" },
    { "do_action_static/gDoActionFasterENGTex", "do_action_static/gDoActionFasterGERTex", "do_action_static/gDoActionFasterFRATex", "do_action_static/gDoActionFasterESPTex" },
    { "do_action_static/gDoActionGrabENGTex", "do_action_static/gDoActionGrabGERTex", "do_action_static/gDoActionGrabFRATex", "do_action_static/gDoActionGrabESPTex" },
    { "do_action_static/gDoActionHookENGTex", "do_action_static/gDoActionHookGERTex", "do_action_static/gDoActionHookFRATex", "do_action_static/gDoActionHookESPTex" },
    { "do_action_static/gDoActionInfoENGTex", "do_action_static/gDoActionInfoGERTex", "do_action_static/gDoActionInfoFRATex", "do_action_static/gDoActionInfoESPTex" },
    { "do_action_static/gDoActionJumpENGTex", "do_action_static/gDoActionJumpGERTex", "do_action_static/gDoActionJumpFRATex", "do_action_static/gDoActionJumpESPTex" },
    { "do_action_static/gDoActionMarchENGTex", "do_action_static/gDoActionMarchGERTex", "do_action_static/gDoActionMarchFRATex", "do_action_static/gDoActionMarchESPTex" },
    { "do_action_static/gDoActionNaviENGTex", "do_action_static/gDoActionNaviGERTex", "do_action_static/gDoActionNaviFRATex", "do_action_static/gDoActionNaviESPTex" },
    { "do_action_static/gDoActionNextENGTex", "do_action_static/gDoActionNextGERTex", "do_action_static/gDoActionNextFRATex", "do_action_static/gDoActionNextESPTex" },
    { "do_action_static/gDoActionNum1ENGTex", "do_action_static/gDoActionNum1GERTex", "do_action_static/gDoActionNum1FRATex", "do_action_static/gDoActionNum1ESPTex" },
    { "do_action_static/gDoActionNum2ENGTex", "do_action_static/gDoActionNum2GERTex", "do_action_static/gDoActionNum2FRATex", "do_action_static/gDoActionNum2ESPTex" },
    { "do_action_static/gDoActionNum3ENGTex", "do_action_static/gDoActionNum3GERTex", "do_action_static/gDoActionNum3FRATex", "do_action_static/gDoActionNum3ESPTex" },
    { "do_action_static/gDoActionNum4ENGTex", "do_action_static/gDoActionNum4GERTex", "do_action_static/gDoActionNum4FRATex", "do_action_static/gDoActionNum4ESPTex" },
    { "do_action_static/gDoActionNum5ENGTex", "do_action_static/gDoActionNum5GERTex", "do_action_static/gDoActionNum5FRATex", "do_action_static/gDoActionNum5ESPTex" },
    { "do_action_static/gDoActionNum6ENGTex", "do_action_static/gDoActionNum6GERTex", "do_action_static/gDoActionNum6FRATex", "do_action_static/gDoActionNum6ESPTex" },
    { "do_action_static/gDoActionNum7ENGTex", "do_action_static/gDoActionNum7GERTex", "do_action_static/gDoActionNum7FRATex", "do_action_static/gDoActionNum7ESPTex" },
    { "do_action_static/gDoActionNum8ENGTex", "do_action_static/gDoActionNum8GERTex", "do_action_static/gDoActionNum8FRATex", "do_action_static/gDoActionNum8ESPTex" },
    { "do_action_static/gDoActionOpenENGTex", "do_action_static/gDoActionOpenGERTex", "do_action_static/gDoActionOpenFRATex", "do_action_static/gDoActionOpenESPTex" },
    { "do_action_static/gDoActionPoundENGTex", "do_action_static/gDoActionPoundGERTex", "do_action_static/gDoActionPoundFRATex", "do_action_static/gDoActionPoundESPTex" },
    { "do_action_static/gDoActionPunchENGTex", "do_action_static/gDoActionPunchGERTex", "do_action_static/gDoActionPunchFRATex", "do_action_static/gDoActionPunchESPTex" },
    { "do_action_static/gDoActionPutAwayENGTex", "do_action_static/gDoActionPutAwayGERTex", "do_action_static/gDoActionPutAwayFRATex", "do_action_static/gDoActionPutAwayESPTex" },
    { "do_action_static/gDoActionQuitENGTex", "do_action_static/gDoActionQuitGERTex", "do_action_static/gDoActionQuitFRATex", "do_action_static/gDoActionQuitESPTex" },
    { "do_action_static/gDoActionReelENGTex", "do_action_static/gDoActionReelGERTex", "do_action_static/gDoActionReelFRATex", "do_action_static/gDoActionReelESPTex" },
    { "do_action_static/gDoActionReturnENGTex", "do_action_static/gDoActionReturnGERTex", "do_action_static/gDoActionReturnFRATex", "do_action_static/gDoActionReturnESPTex" },
    { "do_action_static/gDoActionShootENGTex", "do_action_static/gDoActionShootGERTex", "do_action_static/gDoActionShootFRATex", "do_action_static/gDoActionShootESPTex" },
    { "do_action_static/gDoActionSnapENGTex", "do_action_static/gDoActionSnapGERTex", "do_action_static/gDoActionSnapFRATex", "do_action_static/gDoActionSnapESPTex" },
    { "do_action_static/gDoActionSpeakENGTex", "do_action_static/gDoActionSpeakGERTex", "do_action_static/gDoActionSpeakFRATex", "do_action_static/gDoActionSpeakESPTex" },
    { "do_action_static/gDoActionStopENGTex", "do_action_static/gDoActionStopGERTex", "do_action_static/gDoActionStopFRATex", "do_action_static/gDoActionStopESPTex" },
    { "do_action_static/gDoActionSurfaceENGTex", "do_action_static/gDoActionSurfaceGERTex", "do_action_static/gDoActionSurfaceFRATex", "do_action_static/gDoActionSurfaceESPTex" },
    { "do_action_static/gDoActionSwimENGTex", "do_action_static/gDoActionSwimGERTex", "do_action_static/gDoActionSwimFRATex", "do_action_static/gDoActionSwimESPTex" },
    { "do_action_static/gDoActionThrowENGTex", "do_action_static/gDoActionThrowGERTex", "do_action_static/gDoActionThrowFRATex", "do_action_static/gDoActionThrowESPTex" },
    { "do_action_static/gDoActionWarpENGTex", "do_action_static/gDoActionWarpGERTex", "do_action_static/gDoActionWarpFRATex", "do_action_static/gDoActionWarpESPTex" },
    { "icon_item_jpn_static/gPauseGreatBayTitleENGTex", "icon_item_jpn_static/gPauseGreatBayTitleGERTex", "icon_item_jpn_static/gPauseGreatBayTitleFRATex", "icon_item_jpn_static/gPauseGreatBayTitleESPTex" },
    { "icon_item_jpn_static/gPauseMap10ENGTex", "icon_item_jpn_static/gPauseMap10GERTex", "icon_item_jpn_static/gPauseMap10FRATex", "icon_item_jpn_static/gPauseMap10ESPTex" },
    { "icon_item_jpn_static/gPauseMasks10ENGTex", "icon_item_jpn_static/gPauseMasks10GERTex", "icon_item_jpn_static/gPauseMasks10FRATex", "icon_item_jpn_static/gPauseMasks10ESPTex" },
    { "icon_item_jpn_static/gPauseQuestStatus00ENGTex", "icon_item_jpn_static/gPauseQuestStatus00GERTex", "icon_item_jpn_static/gPauseQuestStatus00FRATex", "icon_item_jpn_static/gPauseQuestStatus00ESPTex" },
    { "icon_item_jpn_static/gPauseQuestStatus10ENGTex", "icon_item_jpn_static/gPauseQuestStatus10GERTex", "icon_item_jpn_static/gPauseQuestStatus10FRATex", "icon_item_jpn_static/gPauseQuestStatus10ESPTex" },
    { "icon_item_jpn_static/gPauseQuestStatus20ENGTex", "icon_item_jpn_static/gPauseQuestStatus20GERTex", "icon_item_jpn_static/gPauseQuestStatus20FRATex", "icon_item_jpn_static/gPauseQuestStatus20ESPTex" },
    { "icon_item_jpn_static/gPauseSelectItem00ENGTex", "icon_item_jpn_static/gPauseSelectItem00GERTex", "icon_item_jpn_static/gPauseSelectItem00FRATex", "icon_item_jpn_static/gPauseSelectItem00ESPTex" },
    { "icon_item_jpn_static/gPauseSelectItem10ENGTex", "icon_item_jpn_static/gPauseSelectItem10GERTex", "icon_item_jpn_static/gPauseSelectItem10FRATex", "icon_item_jpn_static/gPauseSelectItem10ESPTex" },
    { "icon_item_jpn_static/gPauseSelectItem20ENGTex", "icon_item_jpn_static/gPauseSelectItem20GERTex", "icon_item_jpn_static/gPauseSelectItem20FRATex", "icon_item_jpn_static/gPauseSelectItem20ESPTex" },
    { "icon_item_jpn_static/gPauseSnowheadTitleENGTex", "icon_item_jpn_static/gPauseSnowheadTitleGERTex", "icon_item_jpn_static/gPauseSnowheadTitleFRATex", "icon_item_jpn_static/gPauseSnowheadTitleESPTex" },
    { "icon_item_jpn_static/gPauseStoneTowerTitleENGTex", "icon_item_jpn_static/gPauseStoneTowerTitleGERTex", "icon_item_jpn_static/gPauseStoneTowerTitleFRATex", "icon_item_jpn_static/gPauseStoneTowerTitleESPTex" },
    { "icon_item_jpn_static/gPauseToDecideENGTex", "icon_item_jpn_static/gPauseToDecideGERTex", "icon_item_jpn_static/gPauseToDecideFRATex", "icon_item_jpn_static/gPauseToDecideESPTex" },
    { "icon_item_jpn_static/gPauseToEquipENGTex", "icon_item_jpn_static/gPauseToEquipGERTex", "icon_item_jpn_static/gPauseToEquipFRATex", "icon_item_jpn_static/gPauseToEquipESPTex" },
    { "icon_item_jpn_static/gPauseToMapENGTex", "icon_item_jpn_static/gPauseToMapGERTex", "icon_item_jpn_static/gPauseToMapFRATex", "icon_item_jpn_static/gPauseToMapESPTex" },
    { "icon_item_jpn_static/gPauseToMasksENGTex", "icon_item_jpn_static/gPauseToMasksGERTex", "icon_item_jpn_static/gPauseToMasksFRATex", "icon_item_jpn_static/gPauseToMasksESPTex" },
    { "icon_item_jpn_static/gPauseToPlayMelodyENGTex", "icon_item_jpn_static/gPauseToPlayMelodyGERTex", "icon_item_jpn_static/gPauseToPlayMelodyFRATex", "icon_item_jpn_static/gPauseToPlayMelodyESPTex" },
    { "icon_item_jpn_static/gPauseToQuestStatusENGTex", "icon_item_jpn_static/gPauseToQuestStatusGERTex", "icon_item_jpn_static/gPauseToQuestStatusFRATex", "icon_item_jpn_static/gPauseToQuestStatusESPTex" },
    { "icon_item_jpn_static/gPauseToSelectItemENGTex", "icon_item_jpn_static/gPauseToSelectItemGERTex", "icon_item_jpn_static/gPauseToSelectItemFRATex", "icon_item_jpn_static/gPauseToSelectItemESPTex" },
    { "icon_item_jpn_static/gPauseToViewNotebookENGTex", "icon_item_jpn_static/gPauseToViewNotebookGERTex", "icon_item_jpn_static/gPauseToViewNotebookFRATex", "icon_item_jpn_static/gPauseToViewNotebookESPTex" },
    { "icon_item_jpn_static/gPauseWoodfallTitleENGTex", "icon_item_jpn_static/gPauseWoodfallTitleGERTex", "icon_item_jpn_static/gPauseWoodfallTitleFRATex", "icon_item_jpn_static/gPauseWoodfallTitleESPTex" },
    { "item_name_static/gItemNameAllNightMaskENGTex", "item_name_static/gItemNameAllNightMaskGERTex", "item_name_static/gItemNameAllNightMaskFRATex", "item_name_static/gItemNameAllNightMaskESPTex" },
    { "item_name_static/gItemNameBigKeyENGTex", "item_name_static/gItemNameBigKeyGERTex", "item_name_static/gItemNameBigKeyFRATex", "item_name_static/gItemNameBigKeyESPTex" },
    { "item_name_static/gItemNameBigPoeENGTex", "item_name_static/gItemNameBigPoeGERTex", "item_name_static/gItemNameBigPoeFRATex", "item_name_static/gItemNameBigPoeESPTex" },
    { "item_name_static/gItemNameBlastMaskENGTex", "item_name_static/gItemNameBlastMaskGERTex", "item_name_static/gItemNameBlastMaskFRATex", "item_name_static/gItemNameBlastMaskESPTex" },
    { "item_name_static/gItemNameBlueFireENGTex", "item_name_static/gItemNameBlueFireGERTex", "item_name_static/gItemNameBlueFireFRATex", "item_name_static/gItemNameBlueFireESPTex" },
    { "item_name_static/gItemNameBluePotionENGTex", "item_name_static/gItemNameBluePotionGERTex", "item_name_static/gItemNameBluePotionFRATex", "item_name_static/gItemNameBluePotionESPTex" },
    { "item_name_static/gItemNameBombBag20ENGTex", "item_name_static/gItemNameBombBag20GERTex", "item_name_static/gItemNameBombBag20FRATex", "item_name_static/gItemNameBombBag20ESPTex" },
    { "item_name_static/gItemNameBombBag30ENGTex", "item_name_static/gItemNameBombBag30GERTex", "item_name_static/gItemNameBombBag30FRATex", "item_name_static/gItemNameBombBag30ESPTex" },
    { "item_name_static/gItemNameBombBag40ENGTex", "item_name_static/gItemNameBombBag40GERTex", "item_name_static/gItemNameBombBag40FRATex", "item_name_static/gItemNameBombBag40ESPTex" },
    { "item_name_static/gItemNameBombENGTex", "item_name_static/gItemNameBombGERTex", "item_name_static/gItemNameBombFRATex", "item_name_static/gItemNameBombESPTex" },
    { "item_name_static/gItemNameBombchuENGTex", "item_name_static/gItemNameBombchuGERTex", "item_name_static/gItemNameBombchuFRATex", "item_name_static/gItemNameBombchuESPTex" },
    { "item_name_static/gItemNameBombersNotebookENGTex", "item_name_static/gItemNameBombersNotebookGERTex", "item_name_static/gItemNameBombersNotebookFRATex", "item_name_static/gItemNameBombersNotebookESPTex" },
    { "item_name_static/gItemNameBremenMaskENGTex", "item_name_static/gItemNameBremenMaskGERTex", "item_name_static/gItemNameBremenMaskFRATex", "item_name_static/gItemNameBremenMaskESPTex" },
    { "item_name_static/gItemNameBugENGTex", "item_name_static/gItemNameBugGERTex", "item_name_static/gItemNameBugFRATex", "item_name_static/gItemNameBugESPTex" },
    { "item_name_static/gItemNameBunnyHoodENGTex", "item_name_static/gItemNameBunnyHoodGERTex", "item_name_static/gItemNameBunnyHoodFRATex", "item_name_static/gItemNameBunnyHoodESPTex" },
    { "item_name_static/gItemNameCaptainsHatENGTex", "item_name_static/gItemNameCaptainsHatGERTex", "item_name_static/gItemNameCaptainsHatFRATex", "item_name_static/gItemNameCaptainsHatESPTex" },
    { "item_name_static/gItemNameChateauRomaniENGTex", "item_name_static/gItemNameChateauRomaniGERTex", "item_name_static/gItemNameChateauRomaniFRATex", "item_name_static/gItemNameChateauRomaniESPTex" },
    { "item_name_static/gItemNameCircusLeadersMaskENGTex", "item_name_static/gItemNameCircusLeadersMaskGERTex", "item_name_static/gItemNameCircusLeadersMaskFRATex", "item_name_static/gItemNameCircusLeadersMaskESPTex" },
    { "item_name_static/gItemNameCompassENGTex", "item_name_static/gItemNameCompassGERTex", "item_name_static/gItemNameCompassFRATex", "item_name_static/gItemNameCompassESPTex" },
    { "item_name_static/gItemNameCouplesMaskENGTex", "item_name_static/gItemNameCouplesMaskGERTex", "item_name_static/gItemNameCouplesMaskFRATex", "item_name_static/gItemNameCouplesMaskESPTex" },
    { "item_name_static/gItemNameDekuMaskENGTex", "item_name_static/gItemNameDekuMaskGERTex", "item_name_static/gItemNameDekuMaskFRATex", "item_name_static/gItemNameDekuMaskESPTex" },
    { "item_name_static/gItemNameDekuNutENGTex", "item_name_static/gItemNameDekuNutGERTex", "item_name_static/gItemNameDekuNutFRATex", "item_name_static/gItemNameDekuNutESPTex" },
    { "item_name_static/gItemNameDekuPrincessENGTex", "item_name_static/gItemNameDekuPrincessGERTex", "item_name_static/gItemNameDekuPrincessFRATex", "item_name_static/gItemNameDekuPrincessESPTex" },
    { "item_name_static/gItemNameDekuStickENGTex", "item_name_static/gItemNameDekuStickGERTex", "item_name_static/gItemNameDekuStickFRATex", "item_name_static/gItemNameDekuStickESPTex" },
    { "item_name_static/gItemNameDonGerosMaskENGTex", "item_name_static/gItemNameDonGerosMaskGERTex", "item_name_static/gItemNameDonGerosMaskFRATex", "item_name_static/gItemNameDonGerosMaskESPTex" },
    { "item_name_static/gItemNameDungeonMapENGTex", "item_name_static/gItemNameDungeonMapGERTex", "item_name_static/gItemNameDungeonMapFRATex", "item_name_static/gItemNameDungeonMapESPTex" },
    { "item_name_static/gItemNameElegyOfEmptynessENGTex", "item_name_static/gItemNameElegyOfEmptynessGERTex", "item_name_static/gItemNameElegyOfEmptynessFRATex", "item_name_static/gItemNameElegyOfEmptynessESPTex" },
    { "item_name_static/gItemNameEmptyBottleENGTex", "item_name_static/gItemNameEmptyBottleGERTex", "item_name_static/gItemNameEmptyBottleFRATex", "item_name_static/gItemNameEmptyBottleESPTex" },
    { "item_name_static/gItemNameEponasSongENGTex", "item_name_static/gItemNameEponasSongGERTex", "item_name_static/gItemNameEponasSongFRATex", "item_name_static/gItemNameEponasSongESPTex" },
    { "item_name_static/gItemNameFairyENGTex", "item_name_static/gItemNameFairyGERTex", "item_name_static/gItemNameFairyFRATex", "item_name_static/gItemNameFairyESPTex" },
    { "item_name_static/gItemNameFierceDeitysMaskENGTex", "item_name_static/gItemNameFierceDeitysMaskGERTex", "item_name_static/gItemNameFierceDeitysMaskFRATex", "item_name_static/gItemNameFierceDeitysMaskESPTex" },
    { "item_name_static/gItemNameFireArrowENGTex", "item_name_static/gItemNameFireArrowGERTex", "item_name_static/gItemNameFireArrowFRATex", "item_name_static/gItemNameFireArrowESPTex" },
    { "item_name_static/gItemNameFishENGTex", "item_name_static/gItemNameFishGERTex", "item_name_static/gItemNameFishFRATex", "item_name_static/gItemNameFishESPTex" },
    { "item_name_static/gItemNameFullMilkENGTex", "item_name_static/gItemNameFullMilkGERTex", "item_name_static/gItemNameFullMilkFRATex", "item_name_static/gItemNameFullMilkESPTex" },
    { "item_name_static/gItemNameGarosMaskENGTex", "item_name_static/gItemNameGarosMaskGERTex", "item_name_static/gItemNameGarosMaskFRATex", "item_name_static/gItemNameGarosMaskESPTex" },
    { "item_name_static/gItemNameGiantsMaskENGTex", "item_name_static/gItemNameGiantsMaskGERTex", "item_name_static/gItemNameGiantsMaskFRATex", "item_name_static/gItemNameGiantsMaskESPTex" },
    { "item_name_static/gItemNameGibdoMaskENGTex", "item_name_static/gItemNameGibdoMaskGERTex", "item_name_static/gItemNameGibdoMaskFRATex", "item_name_static/gItemNameGibdoMaskESPTex" },
    { "item_name_static/gItemNameGildedSwordENGTex", "item_name_static/gItemNameGildedSwordGERTex", "item_name_static/gItemNameGildedSwordFRATex", "item_name_static/gItemNameGildedSwordESPTex" },
    { "item_name_static/gItemNameGohtsRemainsENGTex", "item_name_static/gItemNameGohtsRemainsGERTex", "item_name_static/gItemNameGohtsRemainsFRATex", "item_name_static/gItemNameGohtsRemainsESPTex" },
    { "item_name_static/gItemNameGoldDustENGTex", "item_name_static/gItemNameGoldDustGERTex", "item_name_static/gItemNameGoldDustFRATex", "item_name_static/gItemNameGoldDustESPTex" },
    { "item_name_static/gItemNameGoronLullabyENGTex", "item_name_static/gItemNameGoronLullabyGERTex", "item_name_static/gItemNameGoronLullabyFRATex", "item_name_static/gItemNameGoronLullabyESPTex" },
    { "item_name_static/gItemNameGoronMaskENGTex", "item_name_static/gItemNameGoronMaskGERTex", "item_name_static/gItemNameGoronMaskFRATex", "item_name_static/gItemNameGoronMaskESPTex" },
    { "item_name_static/gItemNameGreatFairysMaskENGTex", "item_name_static/gItemNameGreatFairysMaskGERTex", "item_name_static/gItemNameGreatFairysMaskFRATex", "item_name_static/gItemNameGreatFairysMaskESPTex" },
    { "item_name_static/gItemNameGreatFairysSwordENGTex", "item_name_static/gItemNameGreatFairysSwordGERTex", "item_name_static/gItemNameGreatFairysSwordFRATex", "item_name_static/gItemNameGreatFairysSwordESPTex" },
    { "item_name_static/gItemNameGreenPotionENGTex", "item_name_static/gItemNameGreenPotionGERTex", "item_name_static/gItemNameGreenPotionFRATex", "item_name_static/gItemNameGreenPotionESPTex" },
    { "item_name_static/gItemNameGyorgsRemainsENGTex", "item_name_static/gItemNameGyorgsRemainsGERTex", "item_name_static/gItemNameGyorgsRemainsFRATex", "item_name_static/gItemNameGyorgsRemainsESPTex" },
    { "item_name_static/gItemNameHalfMilkENGTex", "item_name_static/gItemNameHalfMilkGERTex", "item_name_static/gItemNameHalfMilkFRATex", "item_name_static/gItemNameHalfMilkESPTex" },
    { "item_name_static/gItemNameHerosBowENGTex", "item_name_static/gItemNameHerosBowGERTex", "item_name_static/gItemNameHerosBowFRATex", "item_name_static/gItemNameHerosBowESPTex" },
    { "item_name_static/gItemNameHerosShieldENGTex", "item_name_static/gItemNameHerosShieldGERTex", "item_name_static/gItemNameHerosShieldFRATex", "item_name_static/gItemNameHerosShieldESPTex" },
    { "item_name_static/gItemNameHookshotENGTex", "item_name_static/gItemNameHookshotGERTex", "item_name_static/gItemNameHookshotFRATex", "item_name_static/gItemNameHookshotESPTex" },
    { "item_name_static/gItemNameHotSpringWaterENGTex", "item_name_static/gItemNameHotSpringWaterGERTex", "item_name_static/gItemNameHotSpringWaterFRATex", "item_name_static/gItemNameHotSpringWaterESPTex" },
    { "item_name_static/gItemNameIceArrowENGTex", "item_name_static/gItemNameIceArrowGERTex", "item_name_static/gItemNameIceArrowFRATex", "item_name_static/gItemNameIceArrowESPTex" },
    { "item_name_static/gItemNameKafeisMaskENGTex", "item_name_static/gItemNameKafeisMaskGERTex", "item_name_static/gItemNameKafeisMaskFRATex", "item_name_static/gItemNameKafeisMaskESPTex" },
    { "item_name_static/gItemNameKamarosMaskENGTex", "item_name_static/gItemNameKamarosMaskGERTex", "item_name_static/gItemNameKamarosMaskFRATex", "item_name_static/gItemNameKamarosMaskESPTex" },
    { "item_name_static/gItemNameKeatonMaskENGTex", "item_name_static/gItemNameKeatonMaskGERTex", "item_name_static/gItemNameKeatonMaskFRATex", "item_name_static/gItemNameKeatonMaskESPTex" },
    { "item_name_static/gItemNameKokiriSwordENGTex", "item_name_static/gItemNameKokiriSwordGERTex", "item_name_static/gItemNameKokiriSwordFRATex", "item_name_static/gItemNameKokiriSwordESPTex" },
    { "item_name_static/gItemNameLandTitleDeedENGTex", "item_name_static/gItemNameLandTitleDeedGERTex", "item_name_static/gItemNameLandTitleDeedFRATex", "item_name_static/gItemNameLandTitleDeedESPTex" },
    { "item_name_static/gItemNameLensOfTruthENGTex", "item_name_static/gItemNameLensOfTruthGERTex", "item_name_static/gItemNameLensOfTruthFRATex", "item_name_static/gItemNameLensOfTruthESPTex" },
    { "item_name_static/gItemNameLetterToKafeiENGTex", "item_name_static/gItemNameLetterToKafeiGERTex", "item_name_static/gItemNameLetterToKafeiFRATex", "item_name_static/gItemNameLetterToKafeiESPTex" },
    { "item_name_static/gItemNameLightArrowENGTex", "item_name_static/gItemNameLightArrowGERTex", "item_name_static/gItemNameLightArrowFRATex", "item_name_static/gItemNameLightArrowESPTex" },
    { "item_name_static/gItemNameLullabyIntroENGTex", "item_name_static/gItemNameLullabyIntroGERTex", "item_name_static/gItemNameLullabyIntroFRATex", "item_name_static/gItemNameLullabyIntroESPTex" },
    { "item_name_static/gItemNameMagicBeansENGTex", "item_name_static/gItemNameMagicBeansGERTex", "item_name_static/gItemNameMagicBeansFRATex", "item_name_static/gItemNameMagicBeansESPTex" },
    { "item_name_static/gItemNameMagicalMushroomENGTex", "item_name_static/gItemNameMagicalMushroomGERTex", "item_name_static/gItemNameMagicalMushroomFRATex", "item_name_static/gItemNameMagicalMushroomESPTex" },
    { "item_name_static/gItemNameMaskOfScentsENGTex", "item_name_static/gItemNameMaskOfScentsGERTex", "item_name_static/gItemNameMaskOfScentsFRATex", "item_name_static/gItemNameMaskOfScentsESPTex" },
    { "item_name_static/gItemNameMaskOfTruthENGTex", "item_name_static/gItemNameMaskOfTruthGERTex", "item_name_static/gItemNameMaskOfTruthFRATex", "item_name_static/gItemNameMaskOfTruthESPTex" },
    { "item_name_static/gItemNameMirrorShieldENGTex", "item_name_static/gItemNameMirrorShieldGERTex", "item_name_static/gItemNameMirrorShieldFRATex", "item_name_static/gItemNameMirrorShieldESPTex" },
    { "item_name_static/gItemNameMoonsTearENGTex", "item_name_static/gItemNameMoonsTearGERTex", "item_name_static/gItemNameMoonsTearFRATex", "item_name_static/gItemNameMoonsTearESPTex" },
    { "item_name_static/gItemNameMountainTitleDeedENGTex", "item_name_static/gItemNameMountainTitleDeedGERTex", "item_name_static/gItemNameMountainTitleDeedFRATex", "item_name_static/gItemNameMountainTitleDeedESPTex" },
    { "item_name_static/gItemNameNewWaveBossaNovaENGTex", "item_name_static/gItemNameNewWaveBossaNovaGERTex", "item_name_static/gItemNameNewWaveBossaNovaFRATex", "item_name_static/gItemNameNewWaveBossaNovaESPTex" },
    { "item_name_static/gItemNameOathToOrderENGTex", "item_name_static/gItemNameOathToOrderGERTex", "item_name_static/gItemNameOathToOrderFRATex", "item_name_static/gItemNameOathToOrderESPTex" },
    { "item_name_static/gItemNameOcarinaOfTimeENGTex", "item_name_static/gItemNameOcarinaOfTimeGERTex", "item_name_static/gItemNameOcarinaOfTimeFRATex", "item_name_static/gItemNameOcarinaOfTimeESPTex" },
    { "item_name_static/gItemNameOceanTitleDeedENGTex", "item_name_static/gItemNameOceanTitleDeedGERTex", "item_name_static/gItemNameOceanTitleDeedFRATex", "item_name_static/gItemNameOceanTitleDeedESPTex" },
    { "item_name_static/gItemNameOdolwasRemainsENGTex", "item_name_static/gItemNameOdolwasRemainsGERTex", "item_name_static/gItemNameOdolwasRemainsFRATex", "item_name_static/gItemNameOdolwasRemainsESPTex" },
    { "item_name_static/gItemNamePendantOfMemoriesENGTex", "item_name_static/gItemNamePendantOfMemoriesGERTex", "item_name_static/gItemNamePendantOfMemoriesFRATex", "item_name_static/gItemNamePendantOfMemoriesESPTex" },
    { "item_name_static/gItemNamePictographBoxENGTex", "item_name_static/gItemNamePictographBoxGERTex", "item_name_static/gItemNamePictographBoxFRATex", "item_name_static/gItemNamePictographBoxESPTex" },
    { "item_name_static/gItemNamePieceOfHeartENGTex", "item_name_static/gItemNamePieceOfHeartGERTex", "item_name_static/gItemNamePieceOfHeartFRATex", "item_name_static/gItemNamePieceOfHeartESPTex" },
    { "item_name_static/gItemNamePoeENGTex", "item_name_static/gItemNamePoeGERTex", "item_name_static/gItemNamePoeFRATex", "item_name_static/gItemNamePoeESPTex" },
    { "item_name_static/gItemNamePostmansHatENGTex", "item_name_static/gItemNamePostmansHatGERTex", "item_name_static/gItemNamePostmansHatFRATex", "item_name_static/gItemNamePostmansHatESPTex" },
    { "item_name_static/gItemNamePowderKegENGTex", "item_name_static/gItemNamePowderKegGERTex", "item_name_static/gItemNamePowderKegFRATex", "item_name_static/gItemNamePowderKegESPTex" },
    { "item_name_static/gItemNameQuiver30ENGTex", "item_name_static/gItemNameQuiver30GERTex", "item_name_static/gItemNameQuiver30FRATex", "item_name_static/gItemNameQuiver30ESPTex" },
    { "item_name_static/gItemNameQuiver40ENGTex", "item_name_static/gItemNameQuiver40GERTex", "item_name_static/gItemNameQuiver40FRATex", "item_name_static/gItemNameQuiver40ESPTex" },
    { "item_name_static/gItemNameQuiver50ENGTex", "item_name_static/gItemNameQuiver50GERTex", "item_name_static/gItemNameQuiver50FRATex", "item_name_static/gItemNameQuiver50ESPTex" },
    { "item_name_static/gItemNameRazorSwordENGTex", "item_name_static/gItemNameRazorSwordGERTex", "item_name_static/gItemNameRazorSwordFRATex", "item_name_static/gItemNameRazorSwordESPTex" },
    { "item_name_static/gItemNameRedPotionENGTex", "item_name_static/gItemNameRedPotionGERTex", "item_name_static/gItemNameRedPotionFRATex", "item_name_static/gItemNameRedPotionESPTex" },
    { "item_name_static/gItemNameRomanisMaskENGTex", "item_name_static/gItemNameRomanisMaskGERTex", "item_name_static/gItemNameRomanisMaskFRATex", "item_name_static/gItemNameRomanisMaskESPTex" },
    { "item_name_static/gItemNameRoomKeyENGTex", "item_name_static/gItemNameRoomKeyGERTex", "item_name_static/gItemNameRoomKeyFRATex", "item_name_static/gItemNameRoomKeyESPTex" },
    { "item_name_static/gItemNameSeaHorseENGTex", "item_name_static/gItemNameSeaHorseGERTex", "item_name_static/gItemNameSeaHorseFRATex", "item_name_static/gItemNameSeaHorseESPTex" },
    { "item_name_static/gItemNameSonataOfAwakeningENGTex", "item_name_static/gItemNameSonataOfAwakeningGERTex", "item_name_static/gItemNameSonataOfAwakeningFRATex", "item_name_static/gItemNameSonataOfAwakeningESPTex" },
    { "item_name_static/gItemNameSongOfHealingENGTex", "item_name_static/gItemNameSongOfHealingGERTex", "item_name_static/gItemNameSongOfHealingFRATex", "item_name_static/gItemNameSongOfHealingESPTex" },
    { "item_name_static/gItemNameSongOfSoaringENGTex", "item_name_static/gItemNameSongOfSoaringGERTex", "item_name_static/gItemNameSongOfSoaringFRATex", "item_name_static/gItemNameSongOfSoaringESPTex" },
    { "item_name_static/gItemNameSongOfStormsENGTex", "item_name_static/gItemNameSongOfStormsGERTex", "item_name_static/gItemNameSongOfStormsFRATex", "item_name_static/gItemNameSongOfStormsESPTex" },
    { "item_name_static/gItemNameSongOfTimeENGTex", "item_name_static/gItemNameSongOfTimeGERTex", "item_name_static/gItemNameSongOfTimeFRATex", "item_name_static/gItemNameSongOfTimeESPTex" },
    { "item_name_static/gItemNameSpecialDeliveryToMamaENGTex", "item_name_static/gItemNameSpecialDeliveryToMamaGERTex", "item_name_static/gItemNameSpecialDeliveryToMamaFRATex", "item_name_static/gItemNameSpecialDeliveryToMamaESPTex" },
    { "item_name_static/gItemNameSpringWaterENGTex", "item_name_static/gItemNameSpringWaterGERTex", "item_name_static/gItemNameSpringWaterFRATex", "item_name_static/gItemNameSpringWaterESPTex" },
    { "item_name_static/gItemNameStoneMaskENGTex", "item_name_static/gItemNameStoneMaskGERTex", "item_name_static/gItemNameStoneMaskFRATex", "item_name_static/gItemNameStoneMaskESPTex" },
    { "item_name_static/gItemNameStrayFairiesENGTex", "item_name_static/gItemNameStrayFairiesGERTex", "item_name_static/gItemNameStrayFairiesFRATex", "item_name_static/gItemNameStrayFairiesESPTex" },
    { "item_name_static/gItemNameSwampTitleDeedENGTex", "item_name_static/gItemNameSwampTitleDeedGERTex", "item_name_static/gItemNameSwampTitleDeedFRATex", "item_name_static/gItemNameSwampTitleDeedESPTex" },
    { "item_name_static/gItemNameTwinmoldsRemainsENGTex", "item_name_static/gItemNameTwinmoldsRemainsGERTex", "item_name_static/gItemNameTwinmoldsRemainsFRATex", "item_name_static/gItemNameTwinmoldsRemainsESPTex" },
    { "item_name_static/gItemNameZoraEggENGTex", "item_name_static/gItemNameZoraEggGERTex", "item_name_static/gItemNameZoraEggFRATex", "item_name_static/gItemNameZoraEggESPTex" },
    { "item_name_static/gItemNameZoraMaskENGTex", "item_name_static/gItemNameZoraMaskGERTex", "item_name_static/gItemNameZoraMaskFRATex", "item_name_static/gItemNameZoraMaskESPTex" },
    { "map_name_static/gMapPointClockTownENGTex", "map_name_static/gMapPointClockTownGERTex", "map_name_static/gMapPointClockTownFRATex", "map_name_static/gMapPointClockTownESPTex" },
    { "map_name_static/gMapPointDekuPalaceENGTex", "map_name_static/gMapPointDekuPalaceGERTex", "map_name_static/gMapPointDekuPalaceFRATex", "map_name_static/gMapPointDekuPalaceESPTex" },
    { "map_name_static/gMapPointGoronVillageENGTex", "map_name_static/gMapPointGoronVillageGERTex", "map_name_static/gMapPointGoronVillageFRATex", "map_name_static/gMapPointGoronVillageESPTex" },
    { "map_name_static/gMapPointGreatBayCoastENGTex", "map_name_static/gMapPointGreatBayCoastGERTex", "map_name_static/gMapPointGreatBayCoastFRATex", "map_name_static/gMapPointGreatBayCoastESPTex" },
    { "map_name_static/gMapPointGreatBayENGTex", "map_name_static/gMapPointGreatBayGERTex", "map_name_static/gMapPointGreatBayFRATex", "map_name_static/gMapPointGreatBayESPTex" },
    { "map_name_static/gMapPointIkanaCanyonENGTex", "map_name_static/gMapPointIkanaCanyonGERTex", "map_name_static/gMapPointIkanaCanyonFRATex", "map_name_static/gMapPointIkanaCanyonESPTex" },
    { "map_name_static/gMapPointIkanaGraveyardENGTex", "map_name_static/gMapPointIkanaGraveyardGERTex", "map_name_static/gMapPointIkanaGraveyardFRATex", "map_name_static/gMapPointIkanaGraveyardESPTex" },
    { "map_name_static/gMapPointMilkRoadENGTex", "map_name_static/gMapPointMilkRoadGERTex", "map_name_static/gMapPointMilkRoadFRATex", "map_name_static/gMapPointMilkRoadESPTex" },
    { "map_name_static/gMapPointMountainVillageENGTex", "map_name_static/gMapPointMountainVillageGERTex", "map_name_static/gMapPointMountainVillageFRATex", "map_name_static/gMapPointMountainVillageESPTex" },
    { "map_name_static/gMapPointRomaniRanchENGTex", "map_name_static/gMapPointRomaniRanchGERTex", "map_name_static/gMapPointRomaniRanchFRATex", "map_name_static/gMapPointRomaniRanchESPTex" },
    { "map_name_static/gMapPointSnowheadENGTex", "map_name_static/gMapPointSnowheadGERTex", "map_name_static/gMapPointSnowheadFRATex", "map_name_static/gMapPointSnowheadESPTex" },
    { "map_name_static/gMapPointSouthernSwampENGTex", "map_name_static/gMapPointSouthernSwampGERTex", "map_name_static/gMapPointSouthernSwampFRATex", "map_name_static/gMapPointSouthernSwampESPTex" },
    { "map_name_static/gMapPointStoneTowerENGTex", "map_name_static/gMapPointStoneTowerGERTex", "map_name_static/gMapPointStoneTowerFRATex", "map_name_static/gMapPointStoneTowerESPTex" },
    { "map_name_static/gMapPointWoodfallENGTex", "map_name_static/gMapPointWoodfallGERTex", "map_name_static/gMapPointWoodfallFRATex", "map_name_static/gMapPointWoodfallESPTex" },
    { "map_name_static/gMapPointZoraCapeENGTex", "map_name_static/gMapPointZoraCapeGERTex", "map_name_static/gMapPointZoraCapeFRATex", "map_name_static/gMapPointZoraCapeESPTex" },
    { "map_name_static/gMapPointZoraHallENGTex", "map_name_static/gMapPointZoraHallGERTex", "map_name_static/gMapPointZoraHallFRATex", "map_name_static/gMapPointZoraHallESPTex" },
    { "misc/daytelop_static/gDaytelop24HoursNESTex", "misc/daytelop_static/gDaytelop24HoursGERTex", "misc/daytelop_static/gDaytelop24HoursFRATex", "misc/daytelop_static/gDaytelop24HoursESPTex" },
    { "misc/daytelop_static/gDaytelop48HoursNESTex", "misc/daytelop_static/gDaytelop48HoursGERTex", "misc/daytelop_static/gDaytelop48HoursFRATex", "misc/daytelop_static/gDaytelop48HoursESPTex" },
    { "misc/daytelop_static/gDaytelop72HoursNESTex", "misc/daytelop_static/gDaytelop72HoursGERTex", "misc/daytelop_static/gDaytelop72HoursFRATex", "misc/daytelop_static/gDaytelop72HoursESPTex" },
    { "misc/daytelop_static/gDaytelopFinalDayLeftNESTex", "misc/daytelop_static/gDaytelopFinalDayLeftGERTex", "misc/daytelop_static/gDaytelopFinalDayLeftFRATex", "misc/daytelop_static/gDaytelopFinalDayLeftESPTex" },
    { "misc/daytelop_static/gDaytelopFinalDayRightNESTex", "misc/daytelop_static/gDaytelopFinalDayRightGERTex", "misc/daytelop_static/gDaytelopFinalDayRightFRATex", "misc/daytelop_static/gDaytelopFinalDayRightESPTex" },
    { "misc/daytelop_static/gDaytelopFirstDayLeftNESTex", "misc/daytelop_static/gDaytelopFirstDayLeftGERTex", "misc/daytelop_static/gDaytelopFirstDayLeftFRATex", "misc/daytelop_static/gDaytelopFirstDayLeftESPTex" },
    { "misc/daytelop_static/gDaytelopFirstDayRightNESTex", "misc/daytelop_static/gDaytelopFirstDayRightGERTex", "misc/daytelop_static/gDaytelopFirstDayRightFRATex", "misc/daytelop_static/gDaytelopFirstDayRightESPTex" },
    { "misc/daytelop_static/gDaytelopNewDayLeftNESTex", "misc/daytelop_static/gDaytelopNewDayLeftGERTex", "misc/daytelop_static/gDaytelopNewDayLeftFRATex", "misc/daytelop_static/gDaytelopNewDayLeftESPTex" },
    { "misc/daytelop_static/gDaytelopNewDayRightNESTex", "misc/daytelop_static/gDaytelopNewDayRightGERTex", "misc/daytelop_static/gDaytelopNewDayRightFRATex", "misc/daytelop_static/gDaytelopNewDayRightESPTex" },
    { "misc/daytelop_static/gDaytelopSecondDayLeftNESTex", "misc/daytelop_static/gDaytelopSecondDayLeftGERTex", "misc/daytelop_static/gDaytelopSecondDayLeftFRATex", "misc/daytelop_static/gDaytelopSecondDayLeftESPTex" },
    { "misc/daytelop_static/gDaytelopSecondDayRightNESTex", "misc/daytelop_static/gDaytelopSecondDayRightGERTex", "misc/daytelop_static/gDaytelopSecondDayRightFRATex", "misc/daytelop_static/gDaytelopSecondDayRightESPTex" },
    { "misc/locerrmsg/gNotDesignedForSystemErrorTex", "misc/locerrmsg/gNotDesignedForSystemErrorGERTex", "misc/locerrmsg/gNotDesignedForSystemErrorFRATex", "misc/locerrmsg/gNotDesignedForSystemErrorESPTex" },
    { "misc/title_static/gFileSelAreYouSureCopyENGTex", "misc/title_static/gFileSelAreYouSureCopyGERTex", "misc/title_static/gFileSelAreYouSureCopyFRATex", "misc/title_static/gFileSelAreYouSureCopyESPTex" },
    { "misc/title_static/gFileSelAreYouSureEraseENGTex", "misc/title_static/gFileSelAreYouSureEraseGERTex", "misc/title_static/gFileSelAreYouSureEraseFRATex", "misc/title_static/gFileSelAreYouSureEraseESPTex" },
    { "misc/title_static/gFileSelCheckBrightnessENGTex", "misc/title_static/gFileSelCheckBrightnessGERTex", "misc/title_static/gFileSelCheckBrightnessFRATex", "misc/title_static/gFileSelCheckBrightnessESPTex" },
    { "misc/title_static/gFileSelCopyButtonENGTex", "misc/title_static/gFileSelCopyButtonGERTex", "misc/title_static/gFileSelCopyButtonFRATex", "misc/title_static/gFileSelCopyButtonESPTex" },
    { "misc/title_static/gFileSelCopyToWhichFileENGTex", "misc/title_static/gFileSelCopyToWhichFileGERTex", "misc/title_static/gFileSelCopyToWhichFileFRATex", "misc/title_static/gFileSelCopyToWhichFileESPTex" },
    { "misc/title_static/gFileSelCopyWhichFileENGTex", "misc/title_static/gFileSelCopyWhichFileGERTex", "misc/title_static/gFileSelCopyWhichFileFRATex", "misc/title_static/gFileSelCopyWhichFileESPTex" },
    { "misc/title_static/gFileSelDecideCancelENGTex", "misc/title_static/gFileSelDecideCancelGERTex", "misc/title_static/gFileSelDecideCancelFRATex", "misc/title_static/gFileSelDecideCancelESPTex" },
    { "misc/title_static/gFileSelDecideSaveENGTex", "misc/title_static/gFileSelDecideSaveGERTex", "misc/title_static/gFileSelDecideSaveFRATex", "misc/title_static/gFileSelDecideSaveESPTex" },
    { "misc/title_static/gFileSelENDButtonENGTex", "misc/title_static/gFileSelENDButtonGERTex", "misc/title_static/gFileSelENDButtonFRATex", "misc/title_static/gFileSelENDButtonESPTex" },
    { "misc/title_static/gFileSelEraseButtonENGTex", "misc/title_static/gFileSelEraseButtonGERTex", "misc/title_static/gFileSelEraseButtonFRATex", "misc/title_static/gFileSelEraseButtonESPTex" },
    { "misc/title_static/gFileSelEraseWhichFileENGTex", "misc/title_static/gFileSelEraseWhichFileGERTex", "misc/title_static/gFileSelEraseWhichFileFRATex", "misc/title_static/gFileSelEraseWhichFileESPTex" },
    { "misc/title_static/gFileSelFile1ButtonENGTex", "misc/title_static/gFileSelFile1ButtonGERTex", "misc/title_static/gFileSelFile1ButtonFRATex", "misc/title_static/gFileSelFile1ButtonESPTex" },
    { "misc/title_static/gFileSelFile2ButtonENGTex", "misc/title_static/gFileSelFile2ButtonGERTex", "misc/title_static/gFileSelFile2ButtonFRATex", "misc/title_static/gFileSelFile2ButtonESPTex" },
    { "misc/title_static/gFileSelFile3ButtonENGTex", "misc/title_static/gFileSelFile3ButtonGERTex", "misc/title_static/gFileSelFile3ButtonFRATex", "misc/title_static/gFileSelFile3ButtonESPTex" },
    { "misc/title_static/gFileSelFileCopiedENGTex", "misc/title_static/gFileSelFileCopiedGERTex", "misc/title_static/gFileSelFileCopiedFRATex", "misc/title_static/gFileSelFileCopiedESPTex" },
    { "misc/title_static/gFileSelFileEmptyENGTex", "misc/title_static/gFileSelFileEmptyGERTex", "misc/title_static/gFileSelFileEmptyFRATex", "misc/title_static/gFileSelFileEmptyESPTex" },
    { "misc/title_static/gFileSelFileErasedENGTex", "misc/title_static/gFileSelFileErasedGERTex", "misc/title_static/gFileSelFileErasedFRATex", "misc/title_static/gFileSelFileErasedESPTex" },
    { "misc/title_static/gFileSelFileInUseENGTex", "misc/title_static/gFileSelFileInUseGERTex", "misc/title_static/gFileSelFileInUseFRATex", "misc/title_static/gFileSelFileInUseESPTex" },
    { "misc/title_static/gFileSelFinalDayENGTex", "misc/title_static/gFileSelFinalDayGERTex", "misc/title_static/gFileSelFinalDayFRATex", "misc/title_static/gFileSelFinalDayESPTex" },
    { "misc/title_static/gFileSelFirstDayENGTex", "misc/title_static/gFileSelFirstDayGERTex", "misc/title_static/gFileSelFirstDayFRATex", "misc/title_static/gFileSelFirstDayESPTex" },
    { "misc/title_static/gFileSelHeadsetENGTex", "misc/title_static/gFileSelHeadsetGERTex", "misc/title_static/gFileSelHeadsetFRATex", "misc/title_static/gFileSelHeadsetESPTex" },
    { "misc/title_static/gFileSelHoldENGTex", "misc/title_static/gFileSelHoldGERTex", "misc/title_static/gFileSelHoldFRATex", "misc/title_static/gFileSelHoldESPTex" },
    { "misc/title_static/gFileSelMASKSENGTex", "misc/title_static/gFileSelMASKSGERTex", "misc/title_static/gFileSelMASKSFRATex", "misc/title_static/gFileSelMASKSESPTex" },
    { "misc/title_static/gFileSelMonoENGTex", "misc/title_static/gFileSelMonoGERTex", "misc/title_static/gFileSelMonoFRATex", "misc/title_static/gFileSelMonoESPTex" },
    { "misc/title_static/gFileSelNameENGTex", "misc/title_static/gFileSelNameGERTex", "misc/title_static/gFileSelNameFRATex", "misc/title_static/gFileSelNameESPTex" },
    { "misc/title_static/gFileSelNoEmptyFileENGTex", "misc/title_static/gFileSelNoEmptyFileGERTex", "misc/title_static/gFileSelNoEmptyFileFRATex", "misc/title_static/gFileSelNoEmptyFileESPTex" },
    { "misc/title_static/gFileSelNoFileToCopyENGTex", "misc/title_static/gFileSelNoFileToCopyGERTex", "misc/title_static/gFileSelNoFileToCopyFRATex", "misc/title_static/gFileSelNoFileToCopyESPTex" },
    { "misc/title_static/gFileSelNoFileToEraseENGTex", "misc/title_static/gFileSelNoFileToEraseGERTex", "misc/title_static/gFileSelNoFileToEraseFRATex", "misc/title_static/gFileSelNoFileToEraseESPTex" },
    { "misc/title_static/gFileSelOpenThisFileENGTex", "misc/title_static/gFileSelOpenThisFileGERTex", "misc/title_static/gFileSelOpenThisFileFRATex", "misc/title_static/gFileSelOpenThisFileESPTex" },
    { "misc/title_static/gFileSelOptionsButtonENGTex", "misc/title_static/gFileSelOptionsButtonGERTex", "misc/title_static/gFileSelOptionsButtonFRATex", "misc/title_static/gFileSelOptionsButtonESPTex" },
    { "misc/title_static/gFileSelOptionsENGTex", "misc/title_static/gFileSelOptionsGERTex", "misc/title_static/gFileSelOptionsFRATex", "misc/title_static/gFileSelOptionsESPTex" },
    { "misc/title_static/gFileSelPleaseSelectAFileENGTex", "misc/title_static/gFileSelPleaseSelectAFileGERTex", "misc/title_static/gFileSelPleaseSelectAFileFRATex", "misc/title_static/gFileSelPleaseSelectAFileESPTex" },
    { "misc/title_static/gFileSelPleaseWaitENGTex", "misc/title_static/gFileSelPleaseWaitGERTex", "misc/title_static/gFileSelPleaseWaitFRATex", "misc/title_static/gFileSelPleaseWaitESPTex" },
    { "misc/title_static/gFileSelQuitButtonENGTex", "misc/title_static/gFileSelQuitButtonGERTex", "misc/title_static/gFileSelQuitButtonFRATex", "misc/title_static/gFileSelQuitButtonESPTex" },
    { "misc/title_static/gFileSelSecondDayENGTex", "misc/title_static/gFileSelSecondDayGERTex", "misc/title_static/gFileSelSecondDayFRATex", "misc/title_static/gFileSelSecondDayESPTex" },
    { "misc/title_static/gFileSelSoundENGTex", "misc/title_static/gFileSelSoundGERTex", "misc/title_static/gFileSelSoundFRATex", "misc/title_static/gFileSelSoundESPTex" },
    { "misc/title_static/gFileSelStereoENGTex", "misc/title_static/gFileSelStereoGERTex", "misc/title_static/gFileSelStereoFRATex", "misc/title_static/gFileSelStereoESPTex" },
    { "misc/title_static/gFileSelSwitchENGTex", "misc/title_static/gFileSelSwitchGERTex", "misc/title_static/gFileSelSwitchFRATex", "misc/title_static/gFileSelSwitchESPTex" },
    { "misc/title_static/gFileSelTargetingENGTex", "misc/title_static/gFileSelTargetingGERTex", "misc/title_static/gFileSelTargetingFRATex", "misc/title_static/gFileSelTargetingESPTex" },
    { "misc/title_static/gFileSelYesButtonENGTex", "misc/title_static/gFileSelYesButtonGERTex", "misc/title_static/gFileSelYesButtonFRATex", "misc/title_static/gFileSelYesButtonESPTex" },
    { "objects/object_boss01/gOdolwaTitleCardTex", "objects/object_boss01/gOdolwaTitleCardGERTex", "objects/object_boss01/gOdolwaTitleCardFRATex", "objects/object_boss01/gOdolwaTitleCardESPTex" },
    { "objects/object_boss02/gTwinmoldTitleCardTex", "objects/object_boss02/gTwinmoldTitleCardGERTex", "objects/object_boss02/gTwinmoldTitleCardFRATex", "objects/object_boss02/gTwinmoldTitleCardESPTex" },
    { "objects/object_boss03/gGyorgTitleCardTex", "objects/object_boss03/gGyorgTitleCardGERTex", "objects/object_boss03/gGyorgTitleCardFRATex", "objects/object_boss03/gGyorgTitleCardESPTex" },
    { "objects/object_boss07/gMajorasIncarnationTitleCardTex", "objects/object_boss07/gMajorasIncarnationTitleCardGERTex", "objects/object_boss07/gMajorasIncarnationTitleCardFRATex", "objects/object_boss07/gMajorasIncarnationTitleCardESPTex" },
    { "objects/object_boss07/gMajorasMaskTitleCardTex", "objects/object_boss07/gMajorasMaskTitleCardGERTex", "objects/object_boss07/gMajorasMaskTitleCardFRATex", "objects/object_boss07/gMajorasMaskTitleCardESPTex" },
    { "objects/object_boss07/gMajorasWrathTitleCardTex", "objects/object_boss07/gMajorasWrathTitleCardGERTex", "objects/object_boss07/gMajorasWrathTitleCardFRATex", "objects/object_boss07/gMajorasWrathTitleCardESPTex" },
    { "objects/object_boss_hakugin/gGohtTitleCardTex", "objects/object_boss_hakugin/gGohtTitleCardGERTex", "objects/object_boss_hakugin/gGohtTitleCardFRATex", "objects/object_boss_hakugin/gGohtTitleCardESPTex" },
    { "objects/object_mag/gTitleScreenControllerNotConnectedTextTex", "objects/object_mag/gTitleScreenControllerNotConnectedTextGERTex", "objects/object_mag/gTitleScreenControllerNotConnectedTextFRATex", "objects/object_mag/gTitleScreenControllerNotConnectedTextESPTex" },
    { "objects/object_mag/gTitleScreenInsertControllerTextTex", "objects/object_mag/gTitleScreenInsertControllerTextGERTex", "objects/object_mag/gTitleScreenInsertControllerTextFRATex", "objects/object_mag/gTitleScreenInsertControllerTextESPTex" },
    { "parameter_static/gMinigameCountdownGoTex", "parameter_static/gMinigameCountdownGoGERTex", "parameter_static/gMinigameCountdownGoFRATex", "parameter_static/gMinigameCountdownGoESPTex" },
    { "parameter_static/gPerfectLetterExclamationTex", "parameter_static/gPerfectLetterExclamationGERTex", "parameter_static/gPerfectLetterExclamationFRATex", "" },
    { "parameter_static/gTatlCUpENGTex", "parameter_static/gTatlCUpGERTex", "parameter_static/gTatlCUpFRATex", "parameter_static/gTatlCUpESPTex" },
    { "schedule_static/gBombersNotebookDay1stENGTex", "schedule_static/gBombersNotebookDay1stGERTex", "schedule_static/gBombersNotebookDay1stFRATex", "schedule_static/gBombersNotebookDay1stSPATex" },
    { "schedule_static/gBombersNotebookDay2ndENGTex", "schedule_static/gBombersNotebookDay2ndGERTex", "schedule_static/gBombersNotebookDay2ndFRATex", "schedule_static/gBombersNotebookDay2ndSPATex" },
    { "schedule_static/gBombersNotebookDayFinalENGTex", "schedule_static/gBombersNotebookDayFinalGERTex", "schedule_static/gBombersNotebookDayFinalFRATex", "schedule_static/gBombersNotebookDayFinalSPATex" },
    { "schedule_static/gBombersNotebookTimeOfDayENGTex", "schedule_static/gBombersNotebookTimeOfDayGERTex", "schedule_static/gBombersNotebookTimeOfDayFRATex", "schedule_static/gBombersNotebookTimeOfDaySPATex" },
    { "textures/icon_item_static/gContinuePlayingENGTex", "textures/icon_item_static/gContinuePlayingGERTex", "textures/icon_item_static/gContinuePlayingFRATex", "textures/icon_item_static/gContinuePlayingESPTex" },
    { "textures/icon_item_static/gPauseNoENGTex", "textures/icon_item_static/gPauseNoGERTex", "textures/icon_item_static/gPauseNoFRATex", "textures/icon_item_static/gPauseNoESPTex" },
    { "textures/icon_item_static/gPauseSaveConfirmationENGTex", "textures/icon_item_static/gPauseSaveConfirmationGERTex", "textures/icon_item_static/gPauseSaveConfirmationFRATex", "textures/icon_item_static/gPauseSaveConfirmationESPTex" },
    { "textures/icon_item_static/gPauseSavePromptENGTex", "textures/icon_item_static/gPauseSavePromptGERTex", "textures/icon_item_static/gPauseSavePromptFRATex", "textures/icon_item_static/gPauseSavePromptESPTex" },
    { "textures/icon_item_static/gPauseYesENGTex", "textures/icon_item_static/gPauseYesGERTex", "textures/icon_item_static/gPauseYesFRATex", "textures/icon_item_static/gPauseYesESPTex" },
    { "week_static/gClockDay1stTex", "week_static/gClockDay1stGERTex", "week_static/gClockDay1stFRATex", "week_static/gClockDay1stESPTex" },
    { "week_static/gClockDay2ndTex", "week_static/gClockDay2ndGERTex", "week_static/gClockDay2ndFRATex", "week_static/gClockDay2ndESPTex" },
    { "week_static/gClockDayFinalTex", "week_static/gClockDayFinalGERTex", "week_static/gClockDayFinalFRATex", "week_static/gClockDayFinalESPTex" },
}};

inline std::string Resolve(const std::string& path, u8 language) {
    const auto it = std::lower_bound(kEntries.begin(), kEntries.end(), std::string_view(path),
                                     [](const Entry& entry, std::string_view value) { return entry.base < value; });
    if ((it == kEntries.end()) || (it->base != path)) {
        return path;
    }

    std::string_view localized;
    switch (language) {
        case LANGUAGE_GER:
            localized = it->ger;
            break;
        case LANGUAGE_FRE:
            localized = it->fra;
            break;
        case LANGUAGE_SPA:
            localized = it->esp;
            break;
        default:
            return path;
    }

    return localized.empty() ? path : std::string(localized);
}

} // namespace PalAssetLocalization
